(() => {
  const state={data:null,query:"",category:"all",selected:new Set(),open:new Set(),activeStack:null,view:"home"};
  const els={home:document.getElementById("home-view"),toolbar:document.getElementById("library-toolbar"),filters:document.getElementById("filters"),search:document.getElementById("search"),grid:document.getElementById("card-grid"),empty:document.getElementById("empty-state"),count:document.getElementById("result-count"),library:document.getElementById("library-view"),compare:document.getElementById("compare-view"),compareBoard:document.getElementById("compare-board"),presets:document.getElementById("stack-presets"),stackNote:document.getElementById("stack-note"),dock:document.getElementById("compare-dock"),dockLabel:document.getElementById("dock-label"),dockCompare:document.getElementById("dock-compare"),dockClear:document.getElementById("dock-clear"),clearCompare:document.getElementById("clear-compare"),back:document.getElementById("back-to-library"),compareToggle:document.getElementById("compare-toggle"),offline:document.getElementById("offline-pill")};
  const escapeHtml=v=>String(v).replace(/&/g,["&","amp;"].join("")).replace(/</g,["&","lt;"].join("")).replace(/>/g,["&","gt;"].join("")).replace(/"/g,["&","quot;"].join(""));
  const categoryById=id=>state.data.categories.find(c=>c.id===id); const selectedPeptides=()=>state.data.peptides.filter(p=>state.selected.has(p.id));
  const persist=()=>{try{localStorage.setItem("peptide-ref-selected",JSON.stringify([...state.selected]))}catch{}}; const restore=()=>{try{const r=JSON.parse(localStorage.getItem("peptide-ref-selected")||"[]");if(Array.isArray(r))r.slice(0,5).forEach(id=>state.selected.add(id))}catch{}};
  const matches=p=>{if(state.category!=="all"&&p.category!==state.category)return false;const q=state.query.trim().toLowerCase();if(!q)return true;return [p.name,...(p.aka||[]),p.analogy,p.tagline,p.cardDescription,p.bottomLine,p.dose,p.halfLife,p.timing,p.cycling,p.mechanism,...(p.cautions||[]),...(p.supplements||[]),categoryById(p.category)?.label||""].join(" ").toLowerCase().includes(q)};
  const listHtml=items=>`<ul>${items.map(i=>`<li>${escapeHtml(i)}</li>`).join("")}</ul>`;
  const factsHtml=p=>`<dl class="facts"><div class="fact"><dt>Dose</dt><dd>${escapeHtml(p.dose)}</dd></div><div class="fact"><dt>Half-life</dt><dd>${escapeHtml(p.halfLife)}</dd></div><div class="fact"><dt>Timing / food</dt><dd>${escapeHtml(p.timing)}</dd></div><div class="fact"><dt>Cycling</dt><dd>${escapeHtml(p.cycling)}</dd></div></dl>`;
  const jumpAttr=(id,section)=>`data-jump="${id}-${section}"`;

  const retatrutideHtml=p=>{const cat=categoryById(p.category),selected=state.selected.has(p.id),open=state.open.has(p.id);return `<article class="card ${selected?"selected":""} ${open?"is-open":""}" data-id="${p.id}" data-category="${p.category}">
    <div class="card-summary" data-toggle="${p.id}" role="button" tabindex="0" aria-expanded="${open}">
      <div class="badge-row"><span class="badge cat">${escapeHtml(cat?.short||"")}</span></div>
      <h2>Retatrutide</h2><p class="tagline">Triple Metabolic Signal</p><span class="reta-analogy" ${jumpAttr(p.id,"biology")}>Appetite & Fuel Traffic Controller</span>
      <p class="card-desc" ${jumpAttr(p.id,"biology")}>Think of Retatrutide like a traffic controller working across several metabolic signals at once — helping regulate appetite, food intake, and how the body handles fuel.</p>
      <div class="reta-quick" ${jumpAttr(p.id,"dose")}><div><span>Maintenance</span><b>0.5–2 mg weekly</b></div><div><span>Active</span><b>2–6 mg weekly</b></div><div><span>High</span><b>Up to 12 mg weekly</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"dose")}><strong>Dose rule</strong><p>Hold at the lowest dose producing the result you want. Higher is not the destination.</p></div>
      <div class="reta-quick"><div ${jumpAttr(p.id,"cycling")}><span>Cycling</span><b>No routine cycling</b></div><div ${jumpAttr(p.id,"timing")}><span>Timing</span><b>Once weekly</b></div><div ${jumpAttr(p.id,"watch")}><span>Watch for</span><b>GI tolerance · heart rate</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"expect")}><strong>What to expect</strong><p><b>First:</b> less food noise, earlier fullness, smaller meals — sometimes with GI adjustment. <b>Building:</b> glucose handling and metabolic control can improve before you can feel them. <b>Over time:</b> weight, waist and metabolic markers become the better scorecard. Strong nausea is not proof of a better response.</p></div>
    </div>
    <div class="card-details" ${open?"":"hidden"}>
      <aside class="bottom-line"><strong>Bottom line</strong><p>Retatrutide combines GLP-1, GIP and glucagon receptor signaling. The goal is the lowest exposure that keeps producing the desired metabolic response.</p></aside>
      <div class="facts"><div class="fact"><dt>Use pattern</dt><dd>Continuous weekly exposure in human trials; no receptor-reset cycle is established.</dd></div><div class="fact"><dt>Half-life</dt><dd>About 6 days</dd></div><div class="fact" id="${p.id}-dose"><dt>Escalation</dt><dd>Only when the current exposure is no longer accomplishing the goal or a stronger effect is actually needed.</dd></div><div class="fact" id="${p.id}-timing"><dt>Food / timing</dt><dd>Food-independent. Consistent weekly timing matters more than time of day.</dd></div></div>
      <p class="mechanism" id="${p.id}-expect"><span class="mechanism-label">What to expect — early</span>Changes in appetite, food noise, fullness and meal size are often the most noticeable signals. Gastrointestinal adjustment can occur, especially during dose escalation. Feeling more nausea does not mean the metabolic response is better.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — building</span>Some of the important effects are not sensations. Glucose regulation, insulin sensitivity, hepatic metabolism and fat handling can change underneath the surface, so the absence of a dramatic weekly feeling is not the same thing as no biological response.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — longer term</span>Body-weight trend, waist circumference, body composition and metabolically relevant markers such as glucose and A1C become more useful than judging the compound by how strongly an injection feels. Strength and recovery also matter when weight is falling quickly because lean-mass loss is a real tradeoff of aggressive intake reduction.</p>
      <p class="mechanism" id="${p.id}-biology"><span class="mechanism-label">Biology</span>Retatrutide activates three complementary receptors. GLP-1 signaling reduces appetite and supports glucose-dependent insulin secretion. GIP adds insulinotropic and adipose-tissue signaling. Glucagon-receptor activity adds energy-expenditure and hepatic metabolic effects. The practical value is the combined signal, not simply pushing one pathway harder.</p>
      <p class="mechanism"><span class="mechanism-label">Why the dose ladder is not a goal</span>Human trials show meaningful effects at multiple dose levels, with larger average effects at higher exposures but also more dose-related gastrointestinal effects. A higher available dose does not mean a person benefiting at a lower exposure needs to chase it.</p>
      <p class="mechanism" id="${p.id}-cycling"><span class="mechanism-label">Why no routine cycling</span>Retatrutide has been studied as continuous once-weekly therapy rather than as an on/off receptor-reset protocol. There is no established biological cycling requirement. Stopping is a separate decision from cycling and can allow the metabolic pressures being controlled to return.</p>
      <div class="cautions" id="${p.id}-watch"><strong>Watch for</strong><ul><li>Gastrointestinal effects are dose-related; faster escalation can buy side effects without improving the return.</li><li>Heart rate can tick up on this one, more noticeably at higher doses.</li><li>Some people notice tingling or an altered skin sensation at higher doses — usually mild, and rarely a reason to stop.</li><li>Gallbladder issues (gallstones, occasionally inflammation) show up at low rates with this class of compound generally — more likely tied to how fast someone is losing weight than to anything specific to this molecule. New or worsening upper-right abdominal pain is worth paying attention to.</li><li>A modest uptick in urinary tract infections has also been noted.</li><li>Low intake can become counterproductive if protein, hydration, micronutrients, and resistance training are neglected.</li></ul></div>
      <div class="supplements"><strong>What to monitor</strong><ul><li>Appetite / food noise and satiety</li><li>Body-weight and waist trend — not a single weigh-in</li><li>Glucose and A1C when metabolically relevant</li><li>GI tolerance and resting heart rate</li><li>Strength, protein intake, and body composition when weight is falling quickly</li></ul></div>
    </div>
    <div class="card-actions"><button type="button" class="select-btn" data-select="${p.id}" aria-pressed="${selected}">${selected?"Selected":"Add to synergy"}</button><button type="button" class="primary-btn open-btn" data-toggle="${p.id}" aria-expanded="${open}">${open?"Close":"Go deeper"}</button></div>
  </article>`};

  const bpc157Html=p=>{const cat=categoryById(p.category),selected=state.selected.has(p.id),open=state.open.has(p.id);return `<article class="card ${selected?"selected":""} ${open?"is-open":""}" data-id="${p.id}" data-category="${p.category}">
    <div class="card-summary" data-toggle="${p.id}" role="button" tabindex="0" aria-expanded="${open}">
      <div class="badge-row"><span class="badge cat">${escapeHtml(cat?.short||"")}</span></div>
      <h2>BPC-157</h2><p class="tagline">Repair Coordination Signal</p><span class="reta-analogy" ${jumpAttr(p.id,"biology")}>The Foreman</span>
      <p class="card-desc" ${jumpAttr(p.id,"biology")}>Think of it as the construction foreman for injured tissue — it doesn't build anything itself. It gets your body's repair crews to the site faster and keeps them working in an organized way instead of leaving a mess.</p>
      <div class="reta-quick" ${jumpAttr(p.id,"dose")}><div><span>Maintenance</span><b>250 mcg daily</b></div><div><span>Active</span><b>250–500 mcg daily</b></div><div><span>High</span><b>Up to 1 mg daily</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"dose")}><strong>Dose rule</strong><p>Use the lowest exposure that is producing the repair response. Diminishing returns above 1 mg — more is not automatically more repair.</p></div>
      <div class="reta-quick"><div ${jumpAttr(p.id,"cycling")}><span>Cycling</span><b>No established cycling requirement</b></div><div ${jumpAttr(p.id,"timing")}><span>Timing</span><b>Once or twice daily</b></div><div ${jumpAttr(p.id,"watch")}><span>Watch for</span><b>Angiogenesis · cancer history</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"expect")}><strong>What to expect</strong><p><b>First:</b> joints, tendons, and gut are the usual reasons people reach for this — sprains, tears, stomach issues, general recovery. <b>Building:</b> repair signaling, new blood-vessel access, and organized matrix work happen underneath the surface. Nerve, spinal-cord, and heart-protection findings exist too, mostly from animal studies, not people yet. <b>Over time:</b> function, loading tolerance, and whether gut symptoms hold are the better scorecard than whether an injection feels noticeable.</p></div>
    </div>
    <div class="card-details" ${open?"":"hidden"}>
      <aside class="bottom-line"><strong>Bottom line</strong><p>BPC-157 helps your body heal itself by coordinating repair, not by being the building material. Use the lowest exposure that is actually doing that job.</p></aside>
      <aside class="bottom-line" id="${p.id}-cancer"><strong>Cancer</strong><p>Genuinely unresolved. The same blood-vessel-growth mechanism behind every benefit above is exactly what oncology drugs block in existing tumors. No study either direction. Not a casual reach with active or recent cancer history.</p></aside>
      <div class="facts dose-table" id="${p.id}-dose">
        <div class="fact"><dt>Trial-derived</dt><dd>~100–110 mcg/day, scaled from 10 µg/kg rodent dose.</dd></div>
        <div class="fact"><dt>Practical</dt><dd>250 mcg–1 mg/day, split AM/PM ~12h apart. Up to 2 mg short-term for severe acute injury; diminishing returns above 1 mg.</dd></div>
        <div class="fact"><dt>Why they differ</dt><dd>Practical dose is empirical human convention, 2–5× the scaled number — use the practical range for real protocols.</dd></div>
      </div>
      <div class="facts"><div class="fact"><dt>Half-life / PK</dt><dd>~15-min plasma half-life, but effects last 24h+ — triggers a cascade, doesn't need to stay in blood. Gut-stable; systemic oral absorption uncharacterized.</dd></div><div class="fact" id="${p.id}-timing"><dt>Food / timing</dt><dd>Injectable: once daily or split AM/PM ~12h apart. Oral is a gut-local argument, not a stealth systemic route.</dd></div><div class="fact" id="${p.id}-cycling"><dt>Cycling</dt><dd>No evidence of tolerance/downregulation with continuous use — no receptor has been identified to test that. 8–12 week runs track structural repair better than the shorter convention.</dd></div><div class="fact"><dt>Use pattern</dt><dd>Usually 250–500 mcg/day as a small shot under the skin. For gut-specific issues, some people take it by mouth instead.</dd></div></div>
      <p class="mechanism" id="${p.id}-biology"><span class="mechanism-label">Biology</span>Turns on blood-vessel growth two ways (VEGFR2 + eNOS release) and flips the master switch (EGR-1) that pulls repair cells into the area. Resolves inflammation rather than blocking it outright. No dedicated receptor has been identified.</p>
      <p class="mechanism"><span class="mechanism-label">Cardiac</span>In infarct models: eliminates visible infarct damage, normalizes heart-attack blood markers, preserves pump function — same blood-flow mechanism as everywhere else.</p>
      <p class="mechanism"><span class="mechanism-label">Stroke</span>Full functional recovery (motor, memory, balance) in ischemia models via the same blood-flow pathway.</p>
      <p class="mechanism"><span class="mechanism-label">Spinal cord</span>Reduces the injury cascade after cord compression; spasticity resolves in ~2 weeks. Nerve cuts heal faster, thicker, less painful.</p>
      <p class="mechanism"><span class="mechanism-label">Tendon / ligament</span>Strongest, most independently-replicated evidence here — organized collagen along force lines, healed tissue stronger than original.</p>
      <p class="mechanism"><span class="mechanism-label">Bone</span>Heals defects that don't heal untreated, comparable to a graft. Smaller evidence base than soft tissue.</p>
      <p class="mechanism"><span class="mechanism-label">Kidney</span>Protects the injured kidney directly — and protects kidney/liver/lungs as distant organs from injury elsewhere.</p>
      <p class="mechanism"><span class="mechanism-label">Gut</span>Home turf — restores lining integrity, deepest evidence base, only system with real human-trial history.</p>
      <p class="mechanism"><span class="mechanism-label">Lungs</span>Real protection in general lung-injury models. COVID-specific claims are hypothesis only.</p>
      <p class="mechanism"><span class="mechanism-label">Mood</span>Antidepressant-like effect in standard models, tied to serotonin. Not "rapid," not proven via dopamine/HPA.</p>
      <p class="mechanism"><span class="mechanism-label">Metabolic</span>Mechanism would predict better insulin sensitivity — reasoned extrapolation, not directly tested for this compound.</p>
      <p class="mechanism"><span class="mechanism-label">Why the dose ladder is not a goal</span>This is a cascade initiator, not a linear agonist. Once repair pathways are engaged, extra peptide does not keep amplifying the result. Tissue capacity becomes the bottleneck.</p>
      <p class="mechanism"><span class="mechanism-label">Cycling biology</span>No receptor-reset cycle is established. The common 4–6 week on/off rhythm is convention and cost/caution, not downregulation biology. 8–12 week runs match how long organized vessels and collagen actually take to mature.</p>
      <div class="synergy-detail" id="${p.id}-synergy"><strong>Synergy — BPC-157 + TB-500</strong><ul><li>Non-overlapping jobs: local build (foreman) versus systemic mobilization (scaffolding + access crew).</li><li>Complementary on paper. The combination is untested, not proven.</li></ul></div>
      <div class="cautions" id="${p.id}-watch"><strong>Watch for</strong><ul><li>The same "grow new blood vessels" trick that makes it good at healing is the same thing doctors worry about with existing cancer. Nobody has actually tested it either way in someone with cancer.</li><li>Feeling better can arrive before structural tissue has regained strength; pain relief is not proof that loading capacity is fully restored.</li><li>Most of the organ-system drama is animal work, heavily concentrated in one research group. Independent tendon and angiogenesis papers exist; they do not convert rodent findings into human protocols.</li><li>Banned for competitive athletes. A US pharmacy cannot legally compound it right now.</li></ul></div>
      <div class="supplements"><strong>Supportive supplements</strong><ul><li>Vitamin C</li><li>Collagen peptides</li><li>Zinc carnosine</li><li>NAC</li><li>Glutamine</li><li>Silica</li><li>Lysine/Proline</li></ul></div>
      <div class="dose-guide"><strong>What They’re Not Telling You</strong><p>Foreman, not lumber. The 4–6 week cycle is convention, not receptor biology. Oral is for the gut lining, not a stealth systemic route. And "grows new blood vessels" is both the healing trick and the cancer caution — same mechanism.</p></div>
      <p class="regulatory-note">WADA-prohibited (S0). Not FDA-compoundable as of Aug 2026 — July 2026 advisory vote to reverse, not yet enacted.</p>
      <details class="source-tail"><summary>12 sources, verified Aug 2026</summary><p>Full citation list lives in research/BPC-157_Compound_Research.md. Not duplicated on the card.</p></details>
    </div>
    <div class="card-actions"><button type="button" class="select-btn" data-select="${p.id}" aria-pressed="${selected}">${selected?"Selected":"Add to synergy"}</button><button type="button" class="primary-btn open-btn" data-toggle="${p.id}" aria-expanded="${open}">${open?"Close":"Go deeper"}</button></div>
  </article>`};

  const tb500Html=p=>{const cat=categoryById(p.category),selected=state.selected.has(p.id),open=state.open.has(p.id);return `<article class="card ${selected?"selected":""} ${open?"is-open":""}" data-id="${p.id}" data-category="${p.category}">
    <div class="card-summary" data-toggle="${p.id}" role="button" tabindex="0" aria-expanded="${open}">
      <div class="badge-row"><span class="badge cat">${escapeHtml(cat?.short||"")}</span></div>
      <h2>TB-500</h2><p class="tagline">Systemic Repair Mobilization</p><span class="reta-analogy" ${jumpAttr(p.id,"biology")}>Scaffolding + Access Crew</span>
      <p class="card-desc" ${jumpAttr(p.id,"biology")}>Think of damaged tissue as a job site crews cannot easily reach. TB-500 reorganizes the cellular scaffolding that lets repair-related cells move, helps open vascular access, and supports a more organized remodeling environment.</p>
      <div class="synergy-preview" ${jumpAttr(p.id,"synergy")}><span>Pairs Well With…</span><strong>BPC-157 · GHK-Cu · MOTS-c</strong></div>
      <div class="reta-quick" ${jumpAttr(p.id,"dose")}><div><span>Common rhythm</span><b>Twice weekly</b></div><div><span>Acute demand</span><b>Tighter spacing may fit</b></div><div><span>Maintenance</span><b>Intermittent</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"dose")}><strong>Dose-pattern rule</strong><p>Brief exposure can start repair processes that outlast the circulating peptide. More frequent is not automatically more repair; acute injury is the main reason to consider tighter spacing.</p></div>
      <div class="reta-quick"><div ${jumpAttr(p.id,"cycling")}><span>Cycling</span><b>Goal-based courses</b></div><div ${jumpAttr(p.id,"timing")}><span>Timing</span><b>Food-independent</b></div><div ${jumpAttr(p.id,"watch")}><span>Watch for</span><b>Function before feeling</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"expect")}><strong>What to expect</strong><p><b>First:</b> pain, mobility, or recovery may shift before structure is restored. <b>Building:</b> cell migration, vascular access, and tissue remodeling happen underneath the surface. <b>Over time:</b> durable function and loading tolerance are the better scorecard.</p></div>
    </div>
    <div class="card-details" ${open?"":"hidden"}>
      <aside class="bottom-line"><strong>Bottom line</strong><p>TB-500 is not simply an “injury peptide.” Its central job is cellular mobility and tissue access: reorganizing actin so repair-related cells can move, helping vascular crews reach damaged tissue, and supporting remodeling across more than one local site.</p></aside>
      <div class="facts"><div class="fact"><dt>Identity</dt><dd>TB-500 is associated with the N-acetylated seven-amino-acid LKKTETQ fragment from thymosin beta-4’s actin-binding region. Findings from full-length thymosin beta-4 are useful context but are labeled separately when they have not been shown with the fragment.</dd></div><div class="fact"><dt>Exposure</dt><dd>Short circulating exposure; downstream migration, vascular, and remodeling processes can persist after the peptide is no longer present in blood.</dd></div><div class="fact" id="${p.id}-dose"><dt>Practical pattern</dt><dd>Twice-weekly administration is a common practical rhythm. Acute injury can justify closer spacing because repair demand is unusually high; routine daily exposure is not established as proportionally better.</dd></div><div class="fact" id="${p.id}-timing"><dt>Food / timing</dt><dd>Food-independent. A consistent intermittent rhythm matters more than time of day.</dd></div></div>
      <p class="mechanism" id="${p.id}-expect"><span class="mechanism-label">What to expect — early</span>Changes in discomfort, motion, or recovery can occur before repaired tissue has regained strength. Feeling better is permission to assess function, not proof that the structure is ready for unrestricted loading.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — building</span>The less visible work is cell movement, endothelial organization, new vascular access, and remodeling of the damaged environment. Chronic injuries may move slowly because poor perfusion, altered matrix, and fibrosis are deeper bottlenecks than inflammation alone.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — longer term</span>Use durable function as the scorecard: range of motion, tolerance to progressive load, recurring symptoms, recovery between sessions, and imaging when the injury warrants it.</p>
      <p class="mechanism" id="${p.id}-biology"><span class="mechanism-label">Biology — actin and crew mobility</span>Actin is the cell’s internal scaffolding. Its G-actin and F-actin dynamics let cells change shape, form a leading edge, and migrate. The LKKTETQ region interacts with this system, giving TB-500 its clearest identity: it helps make repair-related cells mobile enough to reach and work within damaged tissue.</p>
      <p class="mechanism"><span class="mechanism-label">Vascular access and angiogenesis</span>Fragment-specific and broader thymosin beta-4 models support endothelial migration and angiogenic activity. This is more than “raising VEGF”: repair requires endothelial cells to move, organize, and build access into poorly perfused tissue such as tendon, scarred tissue, or ischemic muscle.</p>
      <p class="mechanism"><span class="mechanism-label">Fibrosis and scar remodeling</span>LKKTETQ-specific cell work shows reduced activation, proliferation, migration, alpha-SMA, and collagen-I behavior in stimulated human hepatic stellate cells through context-specific Akt inhibition. That supports a direct fragment-level anti-fibrotic signal, while broader scar-remodeling claims still require tissue-by-tissue caution.</p>
      <p class="mechanism"><span class="mechanism-label">Systemic reach</span>The mechanism is not dependent on injecting beside an injury. Damage signals help define where repair activity is needed, while the mobility and vascular-access biology is systemic—potentially useful when several tissues or an old, poorly accessible injury are involved.</p>
      <p class="mechanism"><span class="mechanism-label">Muscle and progenitor biology</span>Broader thymosin beta-4 research describes recruitment and migration of muscle progenitor or satellite cells during regeneration. This is biologically consistent with actin-driven mobility, but direct therapeutic outcome evidence for Ac-LKKTETQ in human muscle remains limited.</p>
      <p class="mechanism"><span class="mechanism-label">Emerging nerve-repair biology</span>Schwann-cell migration, remyelination, and axonal repair all depend on cytoskeletal movement. Thymosin beta-4 models make this a credible emerging application; it should be treated as mechanistically promising rather than a settled TB-500 fragment outcome.</p>
      <p class="mechanism" id="${p.id}-cycling"><span class="mechanism-label">Why intermittent use makes biological sense</span>The target is productive remodeling, not continuous maximum actin manipulation. Once migration and vascular programs begin, repeating exposure simply to keep peptide in circulation may add diminishing returns. Defined repair courses and intermittent maintenance are practical patterns; no human trial has established one universal cycle.</p>
      <div class="synergy-detail" id="${p.id}-synergy"><strong>Synergy — why these pairings make sense</strong><ul><li><b>BPC-157 + TB-500:</b> foreman + scaffolding/access crew. BPC-157 helps coordinate local repair conditions while TB-500 improves cellular mobility, vascular access, and systemic reach.</li><li><b>GHK-Cu + TB-500:</b> materials/blueprints + access crew. GHK-Cu supports matrix production and remodeling instructions while TB-500 helps cells enter and reorganize the damaged environment.</li><li><b>MOTS-c + TB-500:</b> power plant + access crew. MOTS-c supports metabolic capacity for energy-intensive repair while TB-500 supports movement and access. This is mechanistic complementarity, not a proven clinical combination.</li></ul></div>
      <div class="cautions" id="${p.id}-watch"><strong>Common mistakes</strong><ul><li>Treating TB-500 as a local injection that must be placed beside the injury.</li><li>Dosing more often simply to keep peptide in the bloodstream, despite the longer downstream biological response.</li><li>Calling every full-length thymosin beta-4 finding a proven Ac-LKKTETQ effect.</li><li>Assuming early pain relief or mobility means tendon, ligament, muscle, or scar tissue is structurally ready.</li><li>Expecting TB-500 to supply collagen, rehabilitation, sleep, protein, or the progressive loading that repair still requires.</li></ul></div>
      <div class="supplements"><strong>What to monitor</strong><ul><li>Pain trend, range of motion, and whether improvement holds between doses</li><li>Progressive tolerance to loading and real-world function</li><li>Recovery between training or rehabilitation sessions</li><li>Swelling, warmth, or other signs that the site remains actively irritated</li><li>Imaging or clinician-guided testing when structural injury severity makes it useful</li></ul></div>
      <p class="mechanism"><span class="mechanism-label">Cancer-mechanism nuance</span>There is no evidence that TB-500 transforms normal cells into cancer. The relevant biological question is whether an existing malignancy could exploit migration or angiogenesis programs that are beneficial in normal repair. Much of the tumor literature concerns full-length thymosin beta-4 expression inside tumors—not exogenous Ac-LKKTETQ—so the mechanism deserves context, not a claim that TB-500 “causes cancer.”</p>
      <div class="dose-guide"><strong>What They’re Not Telling You</strong><p>TB-500’s real identity is access, movement, and remodeling—not generic “healing.” Old injuries may be especially interesting because they can be trapped behind poor blood supply, dysfunctional matrix, and fibrosis. Scar tissue is functional architecture, not just cosmetic residue. Short exposure can start longer repair programs, so more frequent is not automatically better. And BPC-157 and TB-500 are complementary because they occupy different jobs: foreman versus scaffolding and access crew.</p></div>
      <p class="regulatory-note">Research context: Most injected TB-500 outcome claims remain preclinical, mechanistic, or practice-derived. Evidence type determines how confidently each claim is stated; it does not erase useful biology.</p>
    </div>
    <div class="card-actions"><button type="button" class="select-btn" data-select="${p.id}" aria-pressed="${selected}">${selected?"Selected":"Add to synergy"}</button><button type="button" class="primary-btn open-btn" data-toggle="${p.id}" aria-expanded="${open}">${open?"Close":"Go deeper"}</button></div>
  </article>`};

  const ghkcuHtml=p=>{const cat=categoryById(p.category),selected=state.selected.has(p.id),open=state.open.has(p.id);return `<article class="card ${selected?"selected":""} ${open?"is-open":""}" data-id="${p.id}" data-category="${p.category}">
    <div class="card-summary" data-toggle="${p.id}" role="button" tabindex="0" aria-expanded="${open}">
      <div class="badge-row"><span class="badge cat">${escapeHtml(cat?.short||"")}</span></div>
      <h2>GHK-Cu</h2><p class="tagline">Materials & Genomic Remodeling Signal</p><span class="reta-analogy" ${jumpAttr(p.id,"biology")}>Materials & Blueprints</span>
      <p class="card-desc" ${jumpAttr(p.id,"biology")}>Think of it as the materials-delivery and blueprints role on a repair crew — it doesn't coordinate the job (that's BPC-157) or move crews into place (that's TB-500). It delivers copper to the enzymes that need it and resets a large slice of gene expression back toward a repair-oriented, younger-tissue pattern.</p>
      <div class="reta-quick" ${jumpAttr(p.id,"dose")}><div><span>Days 1–15</span><b>1 mg/day SQ</b></div><div><span>Days 16–30</span><b>2 mg/day SQ</b></div><div><span>Maintenance</span><b>1–2 mg 2–3×/week</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"dose")}><strong>Dose rule</strong><p>This titration is a practitioner convention, not a trial-derived number — no controlled human dose-finding trial for injectable GHK-Cu exists at any dose. See the dose table below for a real gap worth knowing about.</p></div>
      <div class="reta-quick"><div ${jumpAttr(p.id,"cycling")}><span>Cycling</span><b>4–8 wks on / 2–4 off</b></div><div ${jumpAttr(p.id,"timing")}><span>Timing</span><b>Anytime · topical 2×/day</b></div><div ${jumpAttr(p.id,"watch")}><span>Watch for</span><b>Copper load · zinc</b></div></div>
      <div class="dose-guide" ${jumpAttr(p.id,"expect")}><strong>What to expect</strong><p><b>Early:</b> mild skin-feel or inflammation changes, better tolerance of training stress. <b>Building:</b> visible skin-quality, wound-healing, or connective-tissue improvement over 2–6 weeks. <b>Longer term:</b> cumulative remodeling — quiet biology is normal, this isn't a stimulant-type effect.</p></div>
    </div>
    <div class="card-details" ${open?"":"hidden"}>
      <aside class="bottom-line"><strong>Bottom line</strong><p>GHK-Cu supplies copper and gene-level remodeling instructions to a repair job — it's the materials and blueprints, not the foreman (BPC-157) or the access crew (TB-500). Use the lowest exposure doing that job, and don't run it indefinitely without checking copper status.</p></aside>
      <aside class="bottom-line" id="${p.id}-copperload"><strong>Long-term copper load</strong><p>The honest open question isn't cancer risk — Pickart's own data, if anything, points toward anti-metastatic gene effects in vitro, though that's thin and single-lab. The real unresolved question is chronic systemic copper load from repeated injectable cycling, which has no long-term human safety data at all. Topical use has decades of safety history because systemic absorption through skin is minimal; injectable use bypasses that margin.</p></aside>
      <div class="facts dose-table" id="${p.id}-dose">
        <div class="fact"><dt>Pickart's own estimate</dt><dd>~100–200 mg for systemic therapeutic action in humans, extrapolated from his group's thigh-injection and intraperitoneal systemic-healing work.</dd></div>
        <div class="fact"><dt>Practical convention</dt><dd>1–2 mg SQ/day, most starting at 1 mg. This is a compounding-pharmacy and practitioner convention, not trial data either.</dd></div>
        <div class="fact"><dt>Why they differ</dt><dd>50–100× apart, and neither number is validated by a controlled human trial. Treat the low convention as conservative, not as a number with real dose-response backing.</dd></div>
      </div>
      <div class="facts"><div class="fact"><dt>Half-life / PK</dt><dd>~0.5–2 hrs plasma — like BPC-157, effects outlast circulating peptide once the gene-expression and copper-delivery signal is engaged.</dd></div><div class="fact" id="${p.id}-timing"><dt>Food / timing</dt><dd>Food-independent. Topical: apply 2×/day.</dd></div><div class="fact" id="${p.id}-cycling"><dt>Cycling</dt><dd>Cycle for copper load and diminishing remodeling return, not classic receptor desensitization — no receptor has been identified to test that. Injectable: 4–8 weeks on, 2–4 off. Topical: can run 8–12 weeks continuously since systemic copper absorption through skin is minimal.</dd></div><div class="fact"><dt>Use pattern</dt><dd>Small SQ shot, or topical 2×/day for skin-focused use.</dd></div></div>
      <p class="mechanism" id="${p.id}-expect"><span class="mechanism-label">What to expect — early</span>Days to two weeks: possible improvement in skin feel, mild reduction in reactive inflammation, better tolerance of training stress.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — building</span>Two to six weeks: visible or measurable skin-quality, wound-healing, or connective-tissue improvement in a supportive protocol.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — longer term</span>Six to twelve weeks: cumulative remodeling effects become more established. Quiet biology is normal — this is not a stimulant-type effect, and GHK-Cu shouldn't be expected to replace BPC-157 or TB-500, or act as a primary metabolic driver.</p>
      <p class="mechanism" id="${p.id}-biology"><span class="mechanism-label">Biology — copper delivery</span>The tripeptide Gly-His-Lys has very high affinity for Cu²⁺ and readily forms the active GHK-Cu complex, feeding copper-dependent enzymes relevant to repair: lysyl oxidase (collagen cross-linking), superoxide dismutase (antioxidant defense), cytochrome c oxidase (cellular respiration). The lysyl-oxidase link is chemically reasonable — copper is its required cofactor — but GHK-Cu specifically activating it is reasoned extrapolation, not a directly-demonstrated finding.</p>
      <p class="mechanism"><span class="mechanism-label">Biology — gene-expression modulation</span>Using the Broad Institute's Connectivity Map, Pickart's group reports GHK is capable of up- and down-regulating at least 4,000 human genes — the source of the "genome reset" framing. Real and citable, but nearly all of this literature traces back to one commercially-invested lab.</p>
      <p class="mechanism"><span class="mechanism-label">Collagen and matrix remodeling</span>The classic in-vivo wound-chamber study (rat model) found GHK-Cu increased type I and III collagen mRNA and glycosaminoglycan content — but explicitly did not increase TGF-β mRNA. A separate COPD lung-fibroblast study found GHK reversed a gene-expression signature tied to reduced TGF-β pathway activity — different tissue, different mechanism. These are not one linked "collagen + TGF-β" effect.</p>
      <p class="mechanism"><span class="mechanism-label">Anti-inflammatory action</span>GHK-Cu reduced TNF-α-induced IL-6 secretion in cultured human dermal fibroblasts — a real, separate finding from its TIMP-1/2 effect on matrix-metalloproteinase balance. The two mechanisms are unrelated even though both are anti-inflammatory in outcome.</p>
      <p class="mechanism"><span class="mechanism-label">Mast cells — recruits, doesn't stabilize</span>GHK-Cu chemoattracts and activates mast cells as part of orchestrating the wound-to-remodeling transition — the opposite mechanism direction from "stabilizes mast cells, reduces histamine," which is how this often gets described in consumer sources. A classic 1985 chemoattractant study found mast cells specifically accumulate at sites releasing glycyl-histidyl-lysine.</p>
      <p class="mechanism"><span class="mechanism-label">A genuine non-obvious insight</span>GHK isn't actually a foreign signal announcing itself for the first time via injection — it's a matrikine. The sequence sits inside the alpha-2(I) chain of type I collagen and inside SPARC, released by ordinary proteolysis whenever extracellular matrix breaks down at an injury site. Injecting it amplifies a signal the body already generates on-site.</p>
      <p class="mechanism"><span class="mechanism-label">LRP1 and annexin A1 — unconfirmed, not disproven</span>Both appear in consumer-source framing but didn't turn up GHK-specific in a direct literature search. That's a real gap in what shows up in that search — not evidence the mechanisms are wrong. Both are mechanistically plausible; treat as reasoned extrapolation with sourcing unconfirmed.</p>
      <div class="synergy-detail" id="${p.id}-synergy"><strong>Synergy — why these pairings make sense</strong><ul><li><b>BPC-157 + GHK-Cu:</b> foreman + materials/blueprints. GHK-Cu supplies copper and gene-level remodeling instructions; BPC-157 coordinates the repair itself.</li><li><b>TB-500 + GHK-Cu:</b> access crew + materials/blueprints. TB-500 gets repair-related cells to the site; GHK-Cu supplies what they need once they arrive.</li><li><b>MOTS-c + GHK-Cu:</b> power plant + materials/blueprints. No shared pathway — parallel, non-overlapping support.</li><li><b>ARA-290 + GHK-Cu:</b> named explicitly in the project's systemic-restoration source for comprehensive neuroprotection. ARA-290 isn't built in the app yet — forward pointer, not an active link.</li><li><b>The "Repair Stack":</b> BPC-157 + TB-500 + GHK-Cu named together as a deliberate trio addressing the structural, vascular, and regenerative aspects of organ damage.</li></ul></div>
      <div class="cautions" id="${p.id}-watch"><strong>Common mistakes</strong><ul><li>Treating it as a "skin peptide" only and missing the systemic remodeling angle.</li><li>Running high doses continuously for months with no off-period, ignoring copper load.</li><li>Expecting it to replace BPC-157 or TB-500 instead of supplying their materials/instructions.</li><li>Confusing well-studied topical cosmetic concentrations with essentially-unstudied injectable systemic dosing.</li><li>Chasing higher doses once the copper-delivery and gene-reset jobs are already engaged at modest exposure.</li></ul></div>
      <div class="supplements"><strong>Supportive supplements</strong>${listHtml(p.supplements)}</div>
      <div class="dose-guide"><strong>What They're Not Telling You</strong><p>Most consumer GHK-Cu content quietly launders topical-cosmetic evidence into implied support for injectable systemic use — the two are genuinely different pharmacokinetic compartments, and the well-controlled human trials all belong to the topical side. Nearly every "reprograms 4,000 genes" claim traces back, directly or indirectly, to one commercially-invested lab. That doesn't make it false — it means it hasn't been stress-tested by anyone without a stake in the answer.</p></div>
      <p class="regulatory-note">Not FDA-approved. Topical GHK-Cu sits in FDA 503A Category 1 (under evaluation); the injectable-route nomination was specifically withdrawn in 2026. Not named on the WADA Prohibited List (checked directly against the 2026 text — BPC-157 is named under S0, TB-500 under S2.3, GHK-Cu is in neither by name), though it plausibly falls under S0/S2.3 catch-all language even unnamed. Contraindicated in Wilson's disease on mechanistic grounds.</p>
      <details class="source-tail"><summary>9 sources, verified Aug 2026</summary><p>Full citation list lives in research/GHK-Cu_Compound_Research.md. Not duplicated on the card.</p></details>
    </div>
    <div class="card-actions"><button type="button" class="select-btn" data-select="${p.id}" aria-pressed="${selected}">${selected?"Selected":"Add to synergy"}</button><button type="button" class="primary-btn open-btn" data-toggle="${p.id}" aria-expanded="${open}">${open?"Close":"Go deeper"}</button></div>
  </article>`};

  const cardHtml=p=>{if(p.id==="retatrutide")return retatrutideHtml(p);if(p.id==="bpc-157")return bpc157Html(p);if(p.id==="tb-500")return tb500Html(p);if(p.id==="ghk-cu")return ghkcuHtml(p);const cat=categoryById(p.category),selected=state.selected.has(p.id),open=state.open.has(p.id);return `<article class="card ${selected?"selected":""} ${open?"is-open":""}" data-id="${p.id}" data-category="${p.category}"><div class="card-summary" data-toggle="${p.id}" role="button" tabindex="0" aria-expanded="${open}"><div class="badge-row"><span class="badge cat">${escapeHtml(cat?.short||"")}</span></div><h2>${escapeHtml(p.name)}</h2>${p.tagline?`<p class="tagline">${escapeHtml(p.tagline)}</p>`:""}${p.aka?.length?`<p class="aka">${escapeHtml(p.aka.join(" · "))}</p>`:""}${p.cardDescription?`<p class="card-desc">${escapeHtml(p.cardDescription)}</p>`:""}<p class="dose-line"><span>Dose</span> ${escapeHtml(p.dose)}</p></div><div class="card-details" ${open?"":"hidden"}>${p.bottomLine?`<aside class="bottom-line"><strong>Bottom line</strong><p>${escapeHtml(p.bottomLine)}</p></aside>`:""}<div class="badge-row detail-badges"><span class="badge analogy">${escapeHtml(p.analogy)}</span></div>${factsHtml(p)}<p class="mechanism"><span class="mechanism-label">Key mechanism</span>${escapeHtml(p.mechanism)}</p><div class="cautions"><strong>Key cautions</strong>${listHtml(p.cautions)}</div><div class="supplements"><strong>Supportive supplements</strong>${listHtml(p.supplements)}</div></div><div class="card-actions"><button type="button" class="select-btn" data-select="${p.id}" aria-pressed="${selected}">${selected?"Selected":"Add to synergy"}</button><button type="button" class="primary-btn open-btn" data-toggle="${p.id}" aria-expanded="${open}">${open?"Close":"Open"}</button></div></article>`};
  const renderFilters=()=>{const chips=[{id:"all",label:"All"},...state.data.categories.map(c=>({id:c.id,label:c.short}))];els.filters.innerHTML=chips.map(c=>`<button type="button" class="chip" role="tab" data-cat="${c.id}" aria-pressed="${state.category===c.id}">${escapeHtml(c.label)}</button>`).join("")};
  const renderLibrary=()=>{const items=state.data.peptides.filter(matches);els.count.textContent=`${items.length} of ${state.data.peptides.length} entries`;els.grid.innerHTML=items.map(cardHtml).join("");els.empty.hidden=items.length>0};
  const renderPresets=()=>{els.presets.innerHTML=state.data.stacks.map(s=>`<button type="button" class="preset" data-stack="${s.id}" aria-pressed="${state.activeStack===s.id}">${escapeHtml(s.name)}</button>`).join("")};
  const renderCompare=()=>{const items=selectedPeptides();els.compareBoard.innerHTML=items.length===0?`<p class="empty">Select 2–5 peptides, or choose a synergy above.</p>`:items.map(p=>`<div class="compare-col">${cardHtml(p)}</div>`).join("");const s=state.data.stacks.find(x=>x.id===state.activeStack);if(s){els.stackNote.hidden=false;els.stackNote.textContent=`${s.subtitle}. ${s.note}`}else els.stackNote.hidden=true};
  const renderDock=()=>{const n=state.selected.size,show=n>0&&state.view==="library";els.dock.hidden=!show;els.compareToggle.hidden=n<2;els.dockLabel.textContent=n===0?"0 selected":n===1?"1 selected · add 1–4 more":`${n} selected`;els.dockCompare.disabled=n<2||n>5;els.dockCompare.textContent=n<2?"Need 2–5":`Compare ${n}`};
  const markNav=view=>document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("active",(view==="compare"?"stacks":view)===b.dataset.nav));
  const setView=view=>{state.view=view;els.home.hidden=view!=="home";els.library.hidden=view!=="library";els.compare.hidden=view!=="compare";els.toolbar.dataset.hidden=view!=="library"?"true":"false";if(view==="library")renderLibrary();if(view==="compare"){renderPresets();renderCompare()}renderDock();markNav(view);window.scrollTo({top:0,behavior:"smooth"})};
  const toggleOpen=id=>{state.open.has(id)?state.open.delete(id):state.open.add(id);state.view==="compare"?renderCompare():renderLibrary()};
  const jumpTo=(id,target)=>{state.open.add(id);state.view==="compare"?renderCompare():renderLibrary();requestAnimationFrame(()=>document.getElementById(target)?.scrollIntoView({behavior:"smooth",block:"start"}))};
  const toggleSelect=id=>{if(state.selected.has(id))state.selected.delete(id);else{if(state.selected.size>=5){els.dockLabel.textContent="Maximum 5 peptides";els.dock.hidden=false;return}state.selected.add(id)}const s=state.data.stacks.find(x=>x.peptideIds.length===state.selected.size&&x.peptideIds.every(pid=>state.selected.has(pid)));state.activeStack=s?s.id:null;persist();state.view==="compare"?renderCompare():renderLibrary();renderDock()};
  const applyStack=id=>{const s=state.data.stacks.find(x=>x.id===id);if(!s)return;state.selected=new Set(s.peptideIds.slice(0,5));state.activeStack=s.id;persist();setView("compare")};
  const onClick=e=>{const nav=e.target.closest("[data-nav]");if(nav){const v=nav.dataset.nav;if(v==="stacks")setView("compare");else if(v==="search"){setView("library");setTimeout(()=>els.search.focus(),250)}else setView(v);return}const jump=e.target.closest("[data-jump]");if(jump){e.stopPropagation();const card=jump.closest(".card");if(card)jumpTo(card.dataset.id,jump.dataset.jump);return}const homeJump=e.target.closest("[data-home-jump]");if(homeJump){document.getElementById(homeJump.dataset.homeJump)?.scrollIntoView({behavior:"smooth"});return}const cat=e.target.closest("[data-cat]");if(cat){state.category=cat.dataset.cat;renderFilters();renderLibrary();return}const select=e.target.closest("[data-select]");if(select){toggleSelect(select.dataset.select);return}const toggle=e.target.closest("[data-toggle]");if(toggle){toggleOpen(toggle.dataset.toggle);return}const stack=e.target.closest("[data-stack]");if(stack)applyStack(stack.dataset.stack)};
  const setOffline=()=>{els.offline.hidden=navigator.onLine};
  const bind=()=>{document.addEventListener("click",onClick);els.search.addEventListener("input",e=>{state.query=e.target.value;renderLibrary()});els.dockCompare.addEventListener("click",()=>setView("compare"));els.compareToggle.addEventListener("click",()=>setView("compare"));els.back.addEventListener("click",()=>setView("library"));const clear=()=>{state.selected.clear();state.activeStack=null;persist();state.view==="compare"?renderCompare():renderLibrary();renderDock()};els.dockClear.addEventListener("click",clear);els.clearCompare.addEventListener("click",clear);document.addEventListener("keydown",e=>{if(e.key!=="Enter"&&e.key!==" ")return;const t=e.target.closest(".card-summary[data-toggle]");if(!t)return;e.preventDefault();toggleOpen(t.dataset.toggle)});window.addEventListener("online",setOffline);window.addEventListener("offline",setOffline)};
  const registerWorker=()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{})};
  const init=async()=>{bind();setOffline();restore();const response=await fetch("./data/peptides.json");state.data=await response.json();renderFilters();renderLibrary();renderDock();setView("home");registerWorker()};
  init().catch(error=>{els.grid.innerHTML="";els.empty.hidden=false;els.empty.textContent="Could not load peptide data. "+error.message});
})();
