(() => {
  const state={data:null,query:"",category:"all",selected:new Set(),open:new Set(),activeStack:null,view:"home"};
  const els={home:document.getElementById("home-view"),toolbar:document.getElementById("library-toolbar"),filters:document.getElementById("filters"),search:document.getElementById("search"),grid:document.getElementById("card-grid"),empty:document.getElementById("empty-state"),count:document.getElementById("result-count"),library:document.getElementById("library-view"),compare:document.getElementById("compare-view"),compareBoard:document.getElementById("compare-board"),presets:document.getElementById("stack-presets"),stackNote:document.getElementById("stack-note"),dock:document.getElementById("compare-dock"),dockLabel:document.getElementById("dock-label"),dockCompare:document.getElementById("dock-compare"),dockClear:document.getElementById("dock-clear"),clearCompare:document.getElementById("clear-compare"),back:document.getElementById("back-to-library"),compareToggle:document.getElementById("compare-toggle"),offline:document.getElementById("offline-pill")};
  const escapeHtml=v=>String(v).replace(/&/g,["&","amp;"].join("")).replace(/</g,["&","lt;"].join("")).replace(/>/g,["&","gt;"].join("")).replace(/"/g,["&","quot;"].join(""));
  const categoryById=id=>state.data.categories.find(c=>c.id===id); const selectedPeptides=()=>state.data.peptides.filter(p=>state.selected.has(p.id));
  const persist=()=>{try{localStorage.setItem("peptide-ref-selected",JSON.stringify([...state.selected]))}catch{}}; const restore=()=>{try{const r=JSON.parse(localStorage.getItem("peptide-ref-selected")||"[]");if(Array.isArray(r))r.slice(0,5).forEach(id=>state.selected.add(id))}catch{}};
  const matches=p=>{if(state.category!=="all"&&p.category!==state.category)return false;const q=state.query.trim().toLowerCase();if(!q)return true;return [p.name,...(p.aka||[]),p.analogy,p.tagline,p.cardDescription,p.bottomLine,p.dose,p.halfLife,p.timing,p.cycling,p.mechanism,...(p.cautions||[]),...(p.supplements||[]),categoryById(p.category)?.label||""].join(" ").toLowerCase().includes(q)};
  const listHtml=items=>`<ul>${items.map(i=>`<li>${escapeHtml(i)}</li>`).join("")}</ul>`;
  const factsHtml=p=>`<dl class="facts"><div class="fact"><dt>Dose</dt><dd>${escapeHtml(p.dose)}</dd></div><div class="fact"><dt>Half-life</dt><dd>${escapeHtml(p.halfLife)}</dd></div><div class="fact"><dt>Timing / food</dt><dd>${escapeHtml(p.timing)}</dd></div><div class="fact"><dt>Cycling</dt><dd>${escapeHtml(p.cycling)}</dd></div></dl>`;

  const retatrutideHtml=p=>{const cat=categoryById(p.category),selected=state.selected.has(p.id),open=state.open.has(p.id);return `<article class="card ${selected?"selected":""} ${open?"is-open":""}" data-id="${p.id}" data-category="${p.category}">
    <div class="card-summary" data-toggle="${p.id}" role="button" tabindex="0" aria-expanded="${open}">
      <div class="badge-row"><span class="badge cat">${escapeHtml(cat?.short||"")}</span></div>
      <h2>Retatrutide</h2><p class="tagline">Triple Metabolic Signal</p><span class="reta-analogy">Analogy · Appetite & Fuel Traffic Controller</span>
      <p class="card-desc">Think of Retatrutide like a traffic controller working across several metabolic signals at once — helping regulate appetite, food intake, and how the body handles fuel.</p>
      <div class="reta-quick"><div><span>Lower range</span><b>1–4 mg weekly</b></div><div><span>Mid range</span><b>4–9 mg weekly</b></div><div><span>Higher studied</span><b>9–12 mg weekly</b></div></div>
      <div class="dose-guide"><strong>Dose rule</strong><p>Hold at the lowest dose producing the result you want. Higher is not the destination.</p></div>
      <div class="reta-quick"><div><span>Cycling</span><b>No routine cycling</b></div><div><span>Timing</span><b>Once weekly</b></div><div><span>Watch for</span><b>GI tolerance · heart rate</b></div></div>
      <div class="dose-guide"><strong>What to expect</strong><p><b>First:</b> less food noise, earlier fullness, smaller meals — sometimes with GI adjustment. <b>Building:</b> glucose handling and metabolic control can improve before you can feel them. <b>Over time:</b> weight, waist and metabolic markers become the better scorecard. Strong nausea is not proof of a better response.</p></div>
    </div>
    <div class="card-details" ${open?"":"hidden"}>
      <aside class="bottom-line"><strong>Bottom line</strong><p>Retatrutide combines GLP-1, GIP and glucagon receptor signaling. The goal is the lowest exposure that keeps producing the desired metabolic response.</p></aside>
      <div class="facts"><div class="fact"><dt>Use pattern</dt><dd>Continuous weekly exposure in human trials; no receptor-reset cycle is established.</dd></div><div class="fact"><dt>Half-life</dt><dd>About 6 days</dd></div><div class="fact"><dt>Escalation</dt><dd>Only when the current exposure is no longer accomplishing the goal or a stronger effect is actually needed.</dd></div><div class="fact"><dt>Food / timing</dt><dd>Food-independent. Consistent weekly timing matters more than time of day.</dd></div></div>
      <p class="mechanism"><span class="mechanism-label">What to expect — early</span>Changes in appetite, food noise, fullness and meal size are often the most noticeable signals. Gastrointestinal adjustment can occur, especially during dose escalation. Feeling more nausea does not mean the metabolic response is better.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — building</span>Some of the important effects are not sensations. Glucose regulation, insulin sensitivity, hepatic metabolism and fat handling can change underneath the surface, so the absence of a dramatic weekly feeling is not the same thing as no biological response.</p>
      <p class="mechanism"><span class="mechanism-label">What to expect — longer term</span>Body-weight trend, waist circumference, body composition and metabolically relevant markers such as glucose and A1C become more useful than judging the compound by how strongly an injection feels. Strength and recovery also matter when weight is falling quickly because lean-mass loss is a real tradeoff of aggressive intake reduction.</p>
      <p class="mechanism"><span class="mechanism-label">Biology</span>Retatrutide activates three complementary receptors. GLP-1 signaling reduces appetite and supports glucose-dependent insulin secretion. GIP adds insulinotropic and adipose-tissue signaling. Glucagon-receptor activity adds energy-expenditure and hepatic metabolic effects. The practical value is the combined signal, not simply pushing one pathway harder.</p>
      <p class="mechanism"><span class="mechanism-label">Why the dose ladder is not a goal</span>Human trials show meaningful effects at multiple dose levels, with larger average effects at higher exposures but also more dose-related gastrointestinal effects. A higher available dose does not mean a person benefiting at a lower exposure needs to chase it.</p>
      <p class="mechanism"><span class="mechanism-label">Why no routine cycling</span>Retatrutide has been studied as continuous once-weekly therapy rather than as an on/off receptor-reset protocol. There is no established biological cycling requirement. Stopping is a separate decision from cycling and can allow the metabolic pressures being controlled to return.</p>
      <div class="cautions"><strong>Watch for</strong><ul><li>Gastrointestinal effects are dose-related; faster escalation can buy side effects without improving the return.</li><li>Heart-rate increases have been observed and were dose-dependent in Phase 2.</li><li>Low intake can become counterproductive if protein, hydration, micronutrients, and resistance training are neglected.</li></ul></div>
      <div class="supplements"><strong>What to monitor</strong><ul><li>Appetite / food noise and satiety</li><li>Body-weight and waist trend — not a single weigh-in</li><li>Glucose and A1C when metabolically relevant</li><li>GI tolerance and resting heart rate</li><li>Strength, protein intake, and body composition when weight is falling quickly</li></ul></div>
    </div>
    <div class="card-actions"><button type="button" class="select-btn" data-select="${p.id}" aria-pressed="${selected}">${selected?"Selected":"Add to synergy"}</button><button type="button" class="primary-btn open-btn" data-toggle="${p.id}" aria-expanded="${open}">${open?"Close":"Go deeper"}</button></div>
  </article>`};

  const cardHtml=p=>{if(p.id==="retatrutide")return retatrutideHtml(p);const cat=categoryById(p.category),selected=state.selected.has(p.id),open=state.open.has(p.id);return `<article class="card ${selected?"selected":""} ${open?"is-open":""}" data-id="${p.id}" data-category="${p.category}"><div class="card-summary" data-toggle="${p.id}" role="button" tabindex="0" aria-expanded="${open}"><div class="badge-row"><span class="badge cat">${escapeHtml(cat?.short||"")}</span></div><h2>${escapeHtml(p.name)}</h2>${p.tagline?`<p class="tagline">${escapeHtml(p.tagline)}</p>`:""}${p.aka?.length?`<p class="aka">${escapeHtml(p.aka.join(" · "))}</p>`:""}${p.cardDescription?`<p class="card-desc">${escapeHtml(p.cardDescription)}</p>`:""}<p class="dose-line"><span>Dose</span> ${escapeHtml(p.dose)}</p></div><div class="card-details" ${open?"":"hidden"}>${p.bottomLine?`<aside class="bottom-line"><strong>Bottom line</strong><p>${escapeHtml(p.bottomLine)}</p></aside>`:""}<div class="badge-row detail-badges"><span class="badge analogy">${escapeHtml(p.analogy)}</span></div>${factsHtml(p)}<p class="mechanism"><span class="mechanism-label">Key mechanism</span>${escapeHtml(p.mechanism)}</p><div class="cautions"><strong>Key cautions</strong>${listHtml(p.cautions)}</div><div class="supplements"><strong>Supportive supplements</strong>${listHtml(p.supplements)}</div></div><div class="card-actions"><button type="button" class="select-btn" data-select="${p.id}" aria-pressed="${selected}">${selected?"Selected":"Add to synergy"}</button><button type="button" class="primary-btn open-btn" data-toggle="${p.id}" aria-expanded="${open}">${open?"Close":"Open"}</button></div></article>`};
  const renderFilters=()=>{const chips=[{id:"all",label:"All"},...state.data.categories.map(c=>({id:c.id,label:c.short}))];els.filters.innerHTML=chips.map(c=>`<button type="button" class="chip" role="tab" data-cat="${c.id}" aria-pressed="${state.category===c.id}">${escapeHtml(c.label)}</button>`).join("")};
  const renderLibrary=()=>{const items=state.data.peptides.filter(matches);els.count.textContent=`${items.length} of ${state.data.peptides.length} entries`;els.grid.innerHTML=items.map(cardHtml).join("");els.empty.hidden=items.length>0};
  const renderPresets=()=>{els.presets.innerHTML=state.data.stacks.map(s=>`<button type="button" class="preset" data-stack="${s.id}" aria-pressed="${state.activeStack===s.id}">${escapeHtml(s.name)}</button>`).join("")};
  const renderCompare=()=>{const items=selectedPeptides();els.compareBoard.innerHTML=items.length===0?`<p class="empty">Select 2–5 peptides, or choose a synergy above.</p>`:items.map(p=>`<div class="compare-col">${cardHtml(p)}</div>`).join("");const s=state.data.stacks.find(x=>x.id===state.activeStack);if(s){els.stackNote.hidden=false;els.stackNote.textContent=`${s.subtitle}. ${s.note}`}else els.stackNote.hidden=true};
  const renderDock=()=>{const n=state.selected.size,show=n>0&&state.view==="library";els.dock.hidden=!show;els.compareToggle.hidden=n<2;els.dockLabel.textContent=n===0?"0 selected":n===1?"1 selected · add 1–4 more":`${n} selected`;els.dockCompare.disabled=n<2||n>5;els.dockCompare.textContent=n<2?"Need 2–5":`Compare ${n}`};
  const markNav=view=>document.querySelectorAll("[data-nav]").forEach(b=>b.classList.toggle("active",(view==="compare"?"stacks":view)===b.dataset.nav));
  const setView=view=>{state.view=view;els.home.hidden=view!=="home";els.library.hidden=view!=="library";els.compare.hidden=view!=="compare";els.toolbar.dataset.hidden=view!=="library"?"true":"false";if(view==="library")renderLibrary();if(view==="compare"){renderPresets();renderCompare()}renderDock();markNav(view);window.scrollTo({top:0,behavior:"smooth"})};
  const toggleOpen=id=>{state.open.has(id)?state.open.delete(id):state.open.add(id);state.view==="compare"?renderCompare():renderLibrary()};
  const toggleSelect=id=>{if(state.selected.has(id))state.selected.delete(id);else{if(state.selected.size>=5){els.dockLabel.textContent="Maximum 5 peptides";els.dock.hidden=false;return}state.selected.add(id)}const s=state.data.stacks.find(x=>x.peptideIds.length===state.selected.size&&x.peptideIds.every(pid=>state.selected.has(pid)));state.activeStack=s?s.id:null;persist();state.view==="compare"?renderCompare():renderLibrary();renderDock()};
  const applyStack=id=>{const s=state.data.stacks.find(x=>x.id===id);if(!s)return;state.selected=new Set(s.peptideIds.slice(0,5));state.activeStack=s.id;persist();setView("compare")};
  const onClick=e=>{const nav=e.target.closest("[data-nav]");if(nav){const v=nav.dataset.nav;if(v==="stacks")setView("compare");else if(v==="search"){setView("library");setTimeout(()=>els.search.focus(),250)}else setView(v);return}const jump=e.target.closest("[data-home-jump]");if(jump){document.getElementById(jump.dataset.homeJump)?.scrollIntoView({behavior:"smooth"});return}const cat=e.target.closest("[data-cat]");if(cat){state.category=cat.dataset.cat;renderFilters();renderLibrary();return}const select=e.target.closest("[data-select]");if(select){toggleSelect(select.dataset.select);return}const toggle=e.target.closest("[data-toggle]");if(toggle){toggleOpen(toggle.dataset.toggle);return}const stack=e.target.closest("[data-stack]");if(stack)applyStack(stack.dataset.stack)};
  const setOffline=()=>{els.offline.hidden=navigator.onLine};
  const bind=()=>{document.addEventListener("click",onClick);els.search.addEventListener("input",e=>{state.query=e.target.value;renderLibrary()});els.dockCompare.addEventListener("click",()=>setView("compare"));els.compareToggle.addEventListener("click",()=>setView("compare"));els.back.addEventListener("click",()=>setView("library"));const clear=()=>{state.selected.clear();state.activeStack=null;persist();state.view==="compare"?renderCompare():renderLibrary();renderDock()};els.dockClear.addEventListener("click",clear);els.clearCompare.addEventListener("click",clear);document.addEventListener("keydown",e=>{if(e.key!=="Enter"&&e.key!==" ")return;const t=e.target.closest(".card-summary[data-toggle]");if(!t)return;e.preventDefault();toggleOpen(t.dataset.toggle)});window.addEventListener("online",setOffline);window.addEventListener("offline",setOffline)};
  const registerWorker=()=>{if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{})};
  const init=async()=>{bind();setOffline();restore();const response=await fetch("./data/peptides.json");state.data=await response.json();renderFilters();renderLibrary();renderDock();setView("home");registerWorker()};
  init().catch(error=>{els.grid.innerHTML="";els.empty.hidden=false;els.empty.textContent="Could not load peptide data. "+error.message});
})();